CREATE DATABASE Veterinaria;
GO

USE Veterinaria;
GO

CREATE TABLE Clinicas(
IdClinica INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(30)NOT NULL,
Endereco VARCHAR(50) NOT NULL 
);
GO

CREATE TABLE Veterinarios(
IdVeterinario INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(30)NOT NULL,
CRV VARCHAR(30),
IdClinica INT FOREIGN KEY REFERENCES Clinicas(IdClinica) 
);
GO

CREATE TABLE Atendimentos(
IdAtendimentos INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(30),
DatadeAtendimento Date,
IdVeterinarios INT FOREIGN KEY REFERENCES Veterinarios(IdVeterinario)
);
GO

CREATE TABLE TiposPets(
IdTipoPet INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(100)
);
GO

CREATE TABLE Racas(
IdRaca INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(100),
IdTipoPet INT FOREIGN KEY REFERENCES TiposPets(IdTipoPet)
);
GO

CREATE TABLE Donos(
IdDono INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(30)
);
GO

CREATE TABLE Pets(
IdPet INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(30)NOT NULL,
DataNascimento DATE,
IdRaca INT FOREIGN KEY REFERENCES Racas(IdRaca),
IdDono INT FOREIGN KEY REFERENCES Donos(IdDono)
);

